# Generated by Django 4.0.4 on 2022-05-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='number',
            field=models.CharField(max_length=13, verbose_name='number'),
        ),
    ]
